import { SessionType } from "@/types/session.type";

export const sessions: SessionType[] = [
  {
    id_pengguna: "ROUAP123456",
    nama_lengkap: "Arya Pratama",
    asal_kampus: "Universitas Indonesia",
    browser: "Google Chrome",
    sistem_operasi: "Windows",
  },
  {
    id_pengguna: "ROUMA123457",
    nama_lengkap: "Maya Ardhani",
    asal_kampus: "Institut Teknologi Bandung",
    browser: "Mozilla Firefox",
    sistem_operasi: "MacOS",
  },
  {
    id_pengguna: "ROUFY123458",
    nama_lengkap: "Fajar Yudha",
    asal_kampus: "Universitas Gadjah Mada",
    browser: "Safari",
    sistem_operasi: "iOS",
  },
  {
    id_pengguna: "ROURA123459",
    nama_lengkap: "Rani Ayu",
    asal_kampus: "Universitas Airlangga",
    browser: "Microsoft Edge",
    sistem_operasi: "Windows",
  },
  {
    id_pengguna: "ROUDE123460",
    nama_lengkap: "Dewi Eka",
    asal_kampus: "Universitas Padjajaran",
    browser: "Google Chrome",
    sistem_operasi: "Linux",
  },
  {
    id_pengguna: "ROUMI123476",
    nama_lengkap: "Mila Pratiwi",
    asal_kampus: "Universitas Islam Negeri Jakarta",
    browser: "Google Chrome",
    sistem_operasi: "Android",
  },
  {
    id_pengguna: "ROUSA123477",
    nama_lengkap: "Santi Rahmawati",
    asal_kampus: "Universitas Pancasila",
    browser: "Mozilla Firefox",
    sistem_operasi: "Android",
  },
  {
    id_pengguna: "ROUMA123478",
    nama_lengkap: "Mario Putra",
    asal_kampus: "Universitas Katolik Indonesia Atma Jaya",
    browser: "Safari",
    sistem_operasi: "iOS",
  },
  {
    id_pengguna: "ROUZA123479",
    nama_lengkap: "Zahra Mutia",
    asal_kampus: "Universitas Jenderal Soedirman",
    browser: "Google Chrome",
    sistem_operasi: "Windows",
  },
  {
    id_pengguna: "ROUAL123480",
    nama_lengkap: "Alfian Surya",
    asal_kampus: "Universitas Negeri Semarang",
    browser: "Microsoft Edge",
    sistem_operasi: "Windows",
  },
  {
    id_pengguna: "ROUMA123481",
    nama_lengkap: "Mahesa Aditya",
    asal_kampus: "Universitas Multimedia Nusantara",
    browser: "Google Chrome",
    sistem_operasi: "Android",
  },
  {
    id_pengguna: "ROUFA123482",
    nama_lengkap: "Farah Nadia",
    asal_kampus: "Universitas Syiah Kuala",
    browser: "Mozilla Firefox",
    sistem_operasi: "MacOS",
  },
  {
    id_pengguna: "ROUSA123483",
    nama_lengkap: "Sasongko Aji",
    asal_kampus: "Universitas Sanata Dharma",
    browser: "Safari",
    sistem_operasi: "Android",
  },
  {
    id_pengguna: "ROUFE123484",
    nama_lengkap: "Ferry Susanto",
    asal_kampus: "Universitas Negeri Malang",
    browser: "Google Chrome",
    sistem_operasi: "Windows",
  },
  {
    id_pengguna: "ROURO123485",
    nama_lengkap: "Roni Prasetyo",
    asal_kampus: "Universitas Udayana",
    browser: "Google Chrome",
    sistem_operasi: "Android",
  },
  {
    id_pengguna: "ROUDI123461",
    nama_lengkap: "Dimas Irawan",
    asal_kampus: "Universitas Diponegoro",
    browser: "Mozilla Firefox",
    sistem_operasi: "Windows",
  },
  {
    id_pengguna: "ROUZI123462",
    nama_lengkap: "Zizi Nurma",
    asal_kampus: "Universitas Brawijaya",
    browser: "Safari",
    sistem_operasi: "MacOS",
  },
  {
    id_pengguna: "ROUBO123463",
    nama_lengkap: "Bobby Pratama",
    asal_kampus: "Institut Pertanian Bogor",
    browser: "Google Chrome",
    sistem_operasi: "Windows",
  },
  {
    id_pengguna: "ROUAL123464",
    nama_lengkap: "Alifa Rahma",
    asal_kampus: "Universitas Hasanuddin",
    browser: "Mozilla Firefox",
    sistem_operasi: "Linux",
  },
  {
    id_pengguna: "ROUDI123465",
    nama_lengkap: "Dina Kusuma",
    asal_kampus: "Universitas Negeri Yogyakarta",
    browser: "Microsoft Edge",
    sistem_operasi: "Windows",
  },
  {
    id_pengguna: "ROUBS654321",
    nama_lengkap: "Bima Suhendra",
    asal_kampus: "Institut Teknologi Bandung",
    browser: "Google Chrome",
    sistem_operasi: "Windows",
  },
  {
    id_pengguna: "ROUCM987654",
    nama_lengkap: "Citra Maharani",
    asal_kampus: "Universitas Gadjah Mada",
    browser: "Safari",
    sistem_operasi: "Mac OS",
  },
  {
    id_pengguna: "ROURI123466",
    nama_lengkap: "Rizki Nur",
    asal_kampus: "Universitas Trisakti",
    browser: "Google Chrome",
    sistem_operasi: "Windows",
  },
  {
    id_pengguna: "ROUWI123467",
    nama_lengkap: "Windi Putri",
    asal_kampus: "Universitas Pelita Harapan",
    browser: "Safari",
    sistem_operasi: "MacOS",
  },
  {
    id_pengguna: "ROUMO123468",
    nama_lengkap: "Mohan Lazuardi",
    asal_kampus: "Universitas Gunadarma",
    browser: "Mozilla Firefox",
    sistem_operasi: "Linux",
  },
  {
    id_pengguna: "ROUBO123469",
    nama_lengkap: "Boni Arifin",
    asal_kampus: "Universitas Muhammadiyah Yogyakarta",
    browser: "Microsoft Edge",
    sistem_operasi: "Windows",
  },
  {
    id_pengguna: "ROUAN123470",
    nama_lengkap: "Andini Saraswati",
    asal_kampus: "Universitas Esa Unggul",
    browser: "Google Chrome",
    sistem_operasi: "Windows",
  },
  {
    id_pengguna: "ROUSA123471",
    nama_lengkap: "Satya Nugroho",
    asal_kampus: "Universitas Tarumanagara",
    browser: "Safari",
    sistem_operasi: "iOS",
  },
  {
    id_pengguna: "ROURA123472",
    nama_lengkap: "Rara Maheswari",
    asal_kampus: "Universitas Paramadina",
    browser: "Mozilla Firefox",
    sistem_operasi: "Windows",
  },
  {
    id_pengguna: "ROUJU123473",
    nama_lengkap: "Junaedi Akbar",
    asal_kampus: "Universitas Mercu Buana",
    browser: "Google Chrome",
    sistem_operasi: "Windows",
  },
  {
    id_pengguna: "ROUAD123474",
    nama_lengkap: "Aditya Pradana",
    asal_kampus: "Universitas Islam Indonesia",
    browser: "Microsoft Edge",
    sistem_operasi: "Windows",
  },
  {
    id_pengguna: "ROUDA123475",
    nama_lengkap: "Daffa Prasetyo",
    asal_kampus: "Universitas Atma Jaya",
    browser: "Mozilla Firefox",
    sistem_operasi: "Linux",
  },
];
